### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by edoradar** [tjensen/fsuipc#12]
Hello, I really enjoy and appreciate your utility!!
I use it at home to do real time test for my sim but I would have a request if possible:
in my 767 simulator that you can see here www.instagram.com/b767simulator 
I use Ubuntu as I run many programs for specific interfaces and is all done around it. plus I use multiple python programs to run systems simulation. bow I can't do realtime testing as I would need to run the fsuipc from the ubuntu computer to then connect via ethernet to the windows client running P3D.

Would it be possible to do that?

Thanks!

**Comment by tjensen** [comment]
@edoradar I'm limited to what is supported by the underlying FSUIPC SDK, which does not run on anything except Windows. See https://forum.simflight.com/topic/9155-fsuipc-for-linux/

I recommend that you run a server process on Windows that talks to P3D via fsuipc and then use sockets to communicate with that server from your Ubuntu system.
